- name: Deploy to Azure Web App
  uses: azure/webapps-deploy@v3
  with:
    app-name: millodent-admin-dev
    slot-name: production
    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    package: frontend-admin/dist

